
spring.datasource.url=jdbc:postgresql://localhost:5432/control2
spring.datasource.username=postgres
spring.datasource.password=martin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080

app.jwt.secret=esta_es_una_clave_muy_secreta_y_larga_para_cumplir_con_los_256_bits

# --- Solo agregas esto para habilitar la seguridad en el 8080 ---
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=una_clave_muy_larga_y_segura_para_el_keystore_de_https
server.ssl.key-store-type=PKCS12