spring.application.name=demo

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/control2_bda
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson JTS module (optional, but good for serializing Geometry types if needed)
spring.jackson.serialization.fail-on-empty-beans=false
