
spring.datasource.url=jdbc:postgresql://localhost:5432/control2
spring.datasource.username=postgres
spring.datasource.password=martin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola (útil para auditar y validar el uso de funciones espaciales en desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080